name: skin_chat_app
description: "A new Flutter project."
publish_to: "none"

version: 1.2.0+54

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter

  #utitlities
  bcrypt: ^1.1.3
  receive_intent: ^0.2.7
  flutter_screenutil: ^5.9.3
  flutter_launcher_icons: ^0.14.3
  flutter_chat_ui: ^1.6.15
  any_link_preview: ^3.0.3
  flutter_chat_core: ^2.1.1
  metadata_fetch: ^0.4.2
  flutter_link_previewer: ^3.2.2
  flutter_chat_types: ^3.6.2
  #  file_picker: ^9.2.0
  internet_connection_checker: ^3.0.1
  lottie: ^3.3.1
  flutter_svg: ^2.1.0
  intl: ^0.20.2
  image_picker: ^1.1.2
  flutter_image_compress: ^2.4.0
  permission_handler: ^12.0.0+1
  csv: ^6.0.0
  open_filex: ^4.7.0
  infinite_scroll_pagination: ^5.0.0
  dio: ^5.8.0+1
  url_launcher: ^6.3.1
  flutter_file_dialog: ^3.0.2
  package_info_plus: ^8.3.0
  flutter_local_notifications: ^19.1.0


  #  state management
  provider: ^6.1.5

  #  form packages
  flutter_form_builder: ^10.0.1
  form_builder_validators: ^11.1.2

  #  firebase and google auth
  firebase_auth: ^5.5.3
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.7
  firebase_storage: ^12.4.5
  firebase_database: ^11.3.5
  firebase_messaging: ^15.2.5
  google_sign_in: ^6.3.0

  #local storage

  path_provider: ^2.1.5
  path: ^1.9.1
  shared_preferences: ^2.5.3
  toastification: ^3.0.2
  flutter_sharing_intent: ^1.1.1

  #  env loader
  flutter_dotenv: ^5.2.1

  #splash screen
  flutter_native_splash: ^2.4.6

  #skeleton loader
  shimmer: ^3.0.0

dependency_overrides:
  intl: ^0.20.2
  archive: ^4.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

# native splash screen configs
flutter_native_splash:
  android: true
  ios: false
  web: false
  color: "#ffffff"
  image: assets/logo/skin-logo.jpg
  color_dark: "#000000"

  android_12:
    image: assets/logo/skin-logo.jpg
    color: "#ffffff"
    color_dark: "#000000"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/skin-logo.jpg"
  min_sdk_android: 21


flutter:
  uses-material-design: true

  assets:
    - assets/lottie/
    - assets/icons/
    - assets/svgs/
    - assets/logo/
    - .env
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 500
